apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-update-agent
  namespace: apfw-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: update-agent
  template:
    metadata:
      labels:
        app: update-agent
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: update-agent
        image: apfw/windows-update-agent:v1.2.0
        env:
        - name: ANSIBLE_COLLECTIONS_PATH
          value: "/etc/ansible/collections"
